name: mizan
description: A Flutter accounting app - Mizan
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization from SDK
  flutter_localizations:
    sdk: flutter

  # UI & state
  provider: ^6.0.5
  cupertino_icons: ^1.0.5
  intl: ^0.20.2

  # Networking & security
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.2
  process_run: ^0.12.2

  # Local storage / sqlite (sqflite + ffi for desktop)
  sqflite: ^2.4.2
  sqflite_common_ffi: any
  path_provider: ^2.0.14
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # فعلاً ارجاعات به فایل‌های assets/ و fonts حذف شدند تا بیلد ویندوز بدون خطا اجرا شود.
  # اگر بعداً فایل فونت IranSans.ttf یا تصاویر را اضافه کردی، این بخش را بازمی‌گردانم.